name: TradePlus
version: 2.53
author: Trophonix
main: com.trophonix.tradeplus.TradePlus
softdepend: [Vault,EnjinMinecraftPlugin,GriefPrevention,PlayerPoints]
commands:
  trade:
    description: Trade command
  tradeplus:
    description: TradePlus admin command
    permission: tradeplus.admin
permissions:
  tradeplus.admin:
    description: TradePlus admin permission
    default: op
    children:
      tradeplus.trade: true